### PR TITLE
Japanese translation is completed

### PR DESCRIPTION
**Pull request by kuragehimekurara1**
Please confirm that the Japanese translation has been completed.

### CODE REVIEW

**Comment by Creckeryop** [comment]
I need to rework a bit it will take a time sorry, don't cancel your pull request

**Comment by Creckeryop** [comment]
Thank you for your work, I just need to add Japanese kanji hiragana katakana textures

**Comment by Creckeryop** [comment]
https://drive.google.com/file/d/1rre0pa6lHNcX2fuNfBfatwyzFod2zHYV/view?usp=sharing
Check this vpk

**Comment by kuragehimekurara1** [comment]
Confirmation of vpk is completed

**Comment by Creckeryop** [comment]
Sorry for long reply, I need to fix something to make a release, there are some glitches I want to fix

**Comment by kuragehimekurara1** [comment]
I understand. Please let me know when the correction is finished.

**Comment by Creckeryop** [comment]
I released

**Comment by Creckeryop** [comment]
Thank you for your work!

**Comment by kuragehimekurara1** [comment]
Thank you for letting us know!  Thank you for your release!

**Pull request merged**
